version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: docker/production-alpine.Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  portfolio-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./tu-proyecto-vue:/app
    restart: unless-stopped