name: CI - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run tests
      run: npm run test:unit
      
    - name: Build project
      run: npm run build
      
    - name: Run linting
      run: npm run lint

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Alpine image
      run: |
        docker build -f docker/production-alpine.Dockerfile -t portfolio-alpine .
        
    - name: Build Standard image
      run: |
        docker build -f docker/production.Dockerfile -t portfolio-standard .